### ISSUE TITLE
Uninstall Gmail Scheduler App

### ISSUE THREAD

**Issue by dhoopes** [webdigi/GmailScheduler#12]
I am a total noob and got this up and running last year sometime. I have since changed my workflow, so I don't want/need it anymore. 

I want to figure out how to uninstall and completely get rid of this app, but I can't find instructions anywhere on how to do so. I don't want the "App Failure" emails to keep coming in and I don't want to just set a filter to auto delete those messages. I want the app totally gone and all of this undone. While I am grateful for free software, it is a failure of the developer to not include uninstall/remove instructions in a prominent location (and in multiple locations). 

thanks, Dan

**Comment by webdigi** [comment]
The uninstall instructions are now added to the homepage https://github.com/webdigi/GmailScheduler

See below
Simply visit the Connected Apps & Services under your Gmail account. 
You can follow this link https://security.google.com/settings/security/permissions?pli=1
Then find Gmail Scheduler -> Click on Gmail Scheduler -> Then Revoke access. Thats it.

**Comment by dhoopes** [comment]
This issue has not been resolved. I am still getting those dang "Summary of failures for Google Apps Script: Gmail Scheduler" emails with failures every 5 minutes. 

I have:
1. Revoked access to Gmail Scheduler using the link above. It is not longer on the list at all. 
2. Used the link on the https://github.com/webdigi/GmailScheduler site to "Uninstall" 
https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/manage/uninstall
3. Deleted all the labels from my gmail settings. 

And I still get the failure emails! This is like a bad malware/virus/trojan horse!! Very unprofessional.

Please help me to get rid of this once and for all.

**Comment by thapar** [comment]
This is a known issue with Google Apps Script:
https://code.google.com/p/google-apps-script-issues/issues/detail?id=143
Did you install this script to your Google Drive in order to run your own
version of it?

**Comment by dhoopes** [comment]
At this point, I can't even remember where I installed it. I have another workflow to accomplish what this script was trying to do. 

How would I even find it on my drive? Just delete it if I find it? 

Searching my drive for 
gmail scheduler (no quotes) finds two results that have nothing to do with this
"gmail scheduler" finds no results

The main thing is that I don't want this at all. I don't care if it's a known issue because I don't want the script or the annoying failure emails. 

Thanks for your help!

**Comment by webdigi** [comment]
as @thapar mentioned. This looks like a known issue.
Looks like you have not installed but just installed normally.
  
Steps
1) Try installing from all accounts just to make sure the scheduler was not linked with another account https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/exec is the official uninstall method.
Are you sure you dont have not used gmail scheduler from any other account? 

2) The failure emails should have a link. Paste the link of the URL that you see.

**Comment by StephenESC** [comment]
Hi there,

I’m having the same issue. I’m getting a daily email stating “Your script, Gmail Scheduler, has recently failed to finish successfully.” even though I already revoked the script’s access through Gmail and uninstalled it using the link you provide through the instructions.

Any insight on a fix would be greatly appreciated.

Cheers.

**Comment by ffsedd** [comment]
It is possible to remove any script trigger by clicking on its x button via:
 spreadsheets - Tools - Script editor - Edit - All your triggers
