### ISSUE TITLE
Scheduled mail sent multiple times

### ISSUE THREAD

**Issue by sjoerdvh** [webdigi/GmailScheduler#15]
A scheduled mail was sent over 100 times to an forgiving acquaintance.

My suspicion;
Mail sender was a Gmail alias. (sent as other email account), so I suspect that because of this the script was not capable of removing the schedule label.

**Comment by webdigi** [comment]
Thanks for your report. Yes, it looks like it was not capable of removing the schedule email. 

The program was able to add labels so we are not sure why it could not remove the labels (as permissions are available). Is it possible to have a screenshot of the email with the labels? None of the other users have reported such an issue so far.

**Comment by sjoerdvh** [comment]
Thx for your reply.
I don't have a screenshot, because I took the 9 am label off. This to make sure it would not get send anymore.
Will try to reproduce soon with an email adress owned by myself.

**Comment by sjoerdvh** [comment]
Did another test and a few things went strange:
The Queue label and the "timestamp label" are removed. The mail is sent, but the mail is for some reason still a draft.(concept)
I also received the following error:
![capture](https://cloud.githubusercontent.com/assets/8004239/6458582/73cef2c0-c185-11e4-8044-21434b02a46d.JPG)

Can it be that the language setting of Gmail has an influence? (for me this is Dutch) 
Thanks already

**Comment by webdigi** [comment]
Thanks for trying this out again.

It looks like gmail cannot remove the label for some weird reason.

Can you please try to uninstall and install the app again?

Uninstall GmailScheduler - https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/manage/uninstall

Then https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/exec run again and approve permissions to add again.

**Comment by sjoerdvh** [comment]
Ok, done. 
Shall I try again?

**Comment by webdigi** [comment]
yes, all the best :+1:

**Comment by webdigi** [comment]
@sjoerdvh - shall we close this?

**Comment by sjoerdvh** [comment]
Okay

Met vriendelijke groet,

Sjoerd van Heummen

Cursusleider/Adviseur
Mobiel: 06-49678282
sjoerd@wordpresscursus.com
www.wordpresscursus.com
Op 18 mrt. 2015 11:49 schreef "Webdigi - Web Development" <
notifications@github.com>:
