### ISSUE TITLE
Cannot open setting page

### ISSUE THREAD

**Issue by tonlam** [webdigi/GmailScheduler#18]
After I authorize the script, it redirects to setting page. But it's blank page
http://prntscr.com/7heaed

**Comment by webdigi** [comment]
Can you please try uninstalling https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/manage/uninstall and install again https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/exec

**Comment by bacizone** [comment]
I had the same problem, tried uninstalling an installing again these links above. 
Uninstall worked fine, but after the install it redirect to the blank page.

Please help.

**Comment by webdigi** [comment]
if you visit the uninstall again does it say uninstalled again?

Can you see gmail scheduler listed on this page?  https://security.google.com/settings/security/permissions?pli=1

**Comment by bacizone** [comment]
Yes, uninstall works fine with the end result text: "Application Gmail Scheduler successfully uninstalled.".

Then I start install again using the link above.
First the text "This app needs authorization to run." then click the Continue button.
I get to the dropdown window " Gmail Scheduler would like to:.... > Click Accept. Now the result is an blank page.
On my permission page "Apps connected to your account" the Gmail Scheduler is listed. 

But there is no setup page at all.

**Comment by webdigi** [comment]
Thanks, did you get a welcome email at all?

**Comment by bacizone** [comment]
Yes, I installed - uninstalled many times and always get a notification email from apps-scripts-notifications@google.com Gmail Scheduler, including:
- What is Gmail Scheduler?
- How can I uninstall Gmail Scheduler? (with the unistall button)
- About Google Apps Script

**Comment by webdigi** [comment]
Thanks. Are you sure that only this one account is signed now? This is very hard to recreate as all our test accounts work fine after installing and installing.

**Comment by bacizone** [comment]
In Gmail, I have two accounts active, but I always tried to subscribe using only the first account in Chrome.

**Comment by webdigi** [comment]
Thanks for your quick replies. is it possible for you to try incognito window?

**Comment by bacizone** [comment]
No, this is the simple Chrome tab, Chrome v45 64-bit version.

**Comment by webdigi** [comment]
Can you please try on incognito or on another browser like firefox or IE by justing logging on to one account. I cant think of anything in the code that will stop the page from showing.

**Comment by bacizone** [comment]
Hm... it seems to be working in Waterfox (the 64-bit version of Firefox). Probably a Chrome extension blocks it.. not sure. The AdBlock is disabled in gmail domain, and it does not block anything on gmail.com domain.

**Comment by bacizone** [comment]
Configuration does not work in Chrome, but I can use to send email with Gmail Scheduler from Chrome fortunately. So this might be a workaround. Extnesion or the multiple account... not sure.

**Comment by webdigi** [comment]
Thanks for that. 

I assume you can use Waterfox to occasionally change configuration as you like. You can always use chrome to use and work with gmail scheduler once the configuration is setup.

**Comment by bacizone** [comment]
Yes, I'll use it that way. 
Thanks!

**Comment by tonlam** [comment]
Yeah, I can open settings page in safar. It's werid that it can't be opened in Chrome

**Comment by bacizone** [comment]
Hello,

I get this message twice already... and a message of mine did not being
sent from the Draft folder.

Your script, Gmail Scheduler, has recently failed to finish successfully. A
summary of the failure(s) is shown below. To configure the triggers for
this script, or change your setting for receiving future failure
notifications, click here
<https://script.google.com/macros/triggers?id=MQNaF6YQcOgbT0K6URU8GLLGU8VaS0f6W>
.

Details:
StartFunctionError MessageTriggerEnd8/3/15 11:53 AMprocessTimerWe're sorry,
we were unable to fetch authorization credentials. Please wait a bit and
try again.time-based8/3/15 11:55 AM

Sincerely,

Google Apps Script

Need help? Visit the Google Apps Script documentation
<http://code.google.com/googleapps/appsscript/>. Please do not reply to
this message. (c) 2015 Google




Your script, Gmail Scheduler, has recently failed to finish successfully. A
summary of the failure(s) is shown below. To configure the triggers for
this script, or change your setting for receiving future failure
notifications, click here
<https://script.google.com/macros/triggers?id=MQNaF6YQcOgbT0K6URU8GLLGU8VaS0f6W>
.

Details:
StartFunctionError MessageTriggerEnd7/22/15 10:48 AMmoveDraftsToInboxCannot
connect to Gmail (line 85, file "Services", project "Gmail Scheduler")
time-based7/22/15 10:50 AM

Sincerely,

Google Apps Script

Need help? Visit the Google Apps Script documentation
<http://code.google.com/googleapps/appsscript/>. Please do not reply to
this message. (c) 2015 Google



Can you check it please?

thansk,
B.
