### ISSUE TITLE
Doesn't seem to work at all

### ISSUE THREAD

**Issue by jfreeman** [webdigi/GmailScheduler#19]
Hi fellas,  I have tried with default time zone and 'hand picked' time zone.  No matter whether I want emails to be sent 1 hour, 2 hours, or some custom time in the future, they are always sent just a minute or so after I 'send' them after applying the labels that should have them waiting in a queue.  

Is it possible any of my ghostery, disconnect, or badger settings are interfering in some way?

**Comment by webdigi** [comment]
Can you please try say 1 week ahead label then refresh the page after 5 minutes and you should see the new labels attached. Please attach a screenshot that you see. it looks like the timezone selection is off.
