### ISSUE TITLE
There's an additional characters once i send message directly to facebook group through email

### ISSUE THREAD

**Issue by Phoenix062704** [webdigi/GmailScheduler#2]
![problem on gmailscheduler](https://cloud.githubusercontent.com/assets/8710278/4202524/93bae0e4-3828-11e4-8c9e-5777ce98babb.png)

Everytime i schedule an email to Facebook, there's a characters added on the original text i send. Example email address is advertisingbasics@groups.facebook.com.

Note:
I send emails on Facebook groups through email to post it to the group automatically without visiting my Facebook account.

Hoping that you will consider solving this concern. Thanks a lot..

**Comment by webdigi** [comment]
Sorry, this could not be recreated under any test condition. We will mark this for review if this is raised by anyone else.
