### ISSUE TITLE
Email are sent immediatly

### ISSUE THREAD

**Issue by pheijms** [webdigi/GmailScheduler#23]
Hi,

Thanks for creating the Gmail Scheduler!

I installed the plugin, but when I send an email, it will be send immediately. When I look at the send items I see that the email has the label e.g.  "GScheduler/Timer/1 hour later".

I don't understand why it don't work. 
Anyone an idea?

Grtz,
Pieter

**Comment by webdigi** [comment]
@pheijms did you press the send button in the email? This was reported in other issues in the past where users click on the SEND button in gmail. All you have to do is set the schedule and then leave the email to out.

**Comment by pheijms** [comment]
@webdigi Thanks for the quick reply.

That's it! 

What a great plugin! Don't understand that not more people use this free plugin. Keep up the good work!
