### ISSUE TITLE
Error: Service using too much computer time for one day

### ISSUE THREAD

**Issue by bacizone** [webdigi/GmailScheduler#31]
Hi,

I am using GmailScheduler, it worked nice so far. 

However I keep getting it more and more often this message, nearly every day:

"Service using too much computer time for one day
Your script, Gmail Scheduler, has recently failed to finish successfully. A summary of the failure(s) is shown below. 
Summary:
Error Message	Count - Service using too much computer time for one day:  45"

Does GmailScheduler still work?

Are you low on CPU resources in the google cloud hence we get this?

Can we ignore it?

thanks,
Baci

**Comment by webdigi** [comment]
Does scheduling still work?

How many labels & schedules do you have in a typical day?

**Comment by bacizone** [comment]
Hi,

Yes scheduling works, however I use it very rarely, like at 3-4 emails a
month.

Today got this message again, every day...

**Comment by webdigi** [comment]
Updated with https://github.com/webdigi/GmailScheduler/commit/077cb359a2ddbc99af622ec76e439a65d76091fb

Please uninstall and install the app again.

**Comment by bacizone** [comment]
Hi,

uninstalled and reinstalled GmailSchedulre again.
Will report if I still get those emails....

thanks,
Baci

**Comment by bacizone** [comment]
Hi,

even after the yesterday reinstall I still keep getting these emails.... I
run just one scheduled email yesterday in order to test the functionality...


SEE BELOW:

Your script, Gmail Scheduler, has recently failed to finish successfully. A
summary of the failure(s) is shown below. To configure the triggers for
this script, or change your setting for receiving future failure
notifications, click here
<https://script.google.com/macros/triggers?id=MQNaF6YQcOgbT0K6URU8GLLGU8VaS0f6W>
.

Summary:
Error MessageCount
Service using too much computer time for one day 36

Details:
StartFunctionError MessageTriggerEnd
7/26/16 5:52 AM processQueue Service using too much computer time for one
day time-based 7/26/16 5:52 AM
7/26/16 5:57 AM processQueue Service using too much computer time for one
day time-based 7/26/16 5:57 AM
7/26/16 6:07 AM processQueue Service using too much computer time for one
day time-based 7/26/16 6:07 AM
7/26/16 6:17 AM processQueue Service using too much computer time for one
day time-based 7/26/16 6:17 AM
7/26/16 6:22 AM processQueue Service using too much computer time for one
day time-based 7/26/16 6:22 AM
7/26/16 6:37 AM processQueue Service using too much computer time for one
day time-based 7/26/16 6:37 AM
7/26/16 6:47 AM processQueue Service using too much computer time for one
day time-based 7/26/16 6:47 AM
7/26/16 6:52 AM processQueue Service using too much computer time for one
day time-based 7/26/16 6:52 AM
7/26/16 6:57 AM processQueue Service using too much computer time for one
day time-based 7/26/16 6:57 AM
7/26/16 7:07 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:07 AM
7/26/16 7:12 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:12 AM
7/26/16 7:17 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:17 AM
7/26/16 7:22 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:22 AM
7/26/16 7:27 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:27 AM
7/26/16 7:32 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:32 AM
7/26/16 7:37 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:37 AM
7/26/16 7:42 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:42 AM
7/26/16 7:47 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:47 AM
7/26/16 7:52 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:52 AM
7/26/16 7:57 AM processQueue Service using too much computer time for one
day time-based 7/26/16 7:57 AM
7/26/16 8:02 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:02 AM
7/26/16 8:07 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:07 AM
7/26/16 8:12 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:12 AM
7/26/16 8:17 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:17 AM
7/26/16 8:22 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:22 AM
7/26/16 8:27 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:27 AM
7/26/16 8:32 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:32 AM
7/26/16 8:37 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:37 AM
7/26/16 8:42 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:42 AM
7/26/16 8:47 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:47 AM
7/26/16 8:52 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:52 AM
7/26/16 8:57 AM processQueue Service using too much computer time for one
day time-based 7/26/16 8:57 AM
7/26/16 9:02 AM processQueue Service using too much computer time for one
day time-based 7/26/16 9:02 AM
7/26/16 9:07 AM processQueue Service using too much computer time for one
day time-based 7/26/16 9:07 AM
7/26/16 9:12 AM processQueue Service using too much computer time for one
day time-based 7/26/16 9:12 AM
7/26/16 9:17 AM processQueue Service using too much computer time for one
day time-based 7/26/16 9:17 AM

Sincerely,

Google Apps Script

Need help? Visit the Google Apps Script documentation
<http://code.google.com/googleapps/appsscript/>. Please do not reply to
this message. (c) 2016 Google

**Comment by webdigi** [comment]
Thanks for reporitng back.

Looks like Google limit. We probably have to reduce the timer further https://developers.google.com/apps-script/guides/services/quotas

**Comment by bacizone** [comment]
Ok, please do that so.

**Comment by bacizone** [comment]
Still coming...

**Comment by bacizone** [comment]
They just keep coming every morning...

Like this:

Your script, Gmail Scheduler, has recently failed to finish successfully. A
summary of the failure(s) is shown below. To configure the triggers for
this script, or change your setting for receiving future failure
notifications, click here
<https://script.google.com/macros/triggers?id=MQNaF6YQcOgbT0K6URU8GLLGU8VaS0f6W>
.

Summary:
Error MessageCount
Service using too much computer time for one day 25

Details:
StartFunctionError MessageTriggerEnd
7/31/16 6:47 AM processQueue Service using too much computer time for one
day time-based 7/31/16 6:47 AM
7/31/16 6:57 AM processQueue Service using too much computer time for one
day time-based 7/31/16 6:57 AM
7/31/16 7:07 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:07 AM
7/31/16 7:12 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:12 AM
7/31/16 7:17 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:17 AM
7/31/16 7:32 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:32 AM
7/31/16 7:42 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:42 AM
7/31/16 7:47 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:47 AM
7/31/16 7:52 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:52 AM
7/31/16 7:57 AM processQueue Service using too much computer time for one
day time-based 7/31/16 7:57 AM
7/31/16 8:02 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:02 AM
7/31/16 8:07 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:07 AM
7/31/16 8:12 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:12 AM
7/31/16 8:17 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:17 AM
7/31/16 8:22 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:22 AM
7/31/16 8:32 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:32 AM
7/31/16 8:37 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:37 AM
7/31/16 8:42 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:42 AM
7/31/16 8:47 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:47 AM
7/31/16 8:52 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:52 AM
7/31/16 8:57 AM processQueue Service using too much computer time for one
day time-based 7/31/16 8:57 AM
7/31/16 9:02 AM processQueue Service using too much computer time for one
day time-based 7/31/16 9:02 AM
7/31/16 9:07 AM processQueue Service using too much computer time for one
day time-based 7/31/16 9:07 AM
7/31/16 9:12 AM processQueue Service using too much computer time for one
day time-based 7/31/16 9:12 AM
7/31/16 9:17 AM processQueue Service using too much computer time for one
day time-based 7/31/16 9:17 AM

Sincerely,

Google Apps Script

Need help? Visit the Google Apps Script documentation
<http://code.google.com/googleapps/appsscript/>. Please do not reply to
this message. (c) 2016 Google
