### ISSUE TITLE
processQueue error

### ISSUE THREAD

**Issue by WorkerBee099** [webdigi/GmailScheduler#34]
Here are two examples of an error that I receive repeatedly...

![image](https://cloud.githubusercontent.com/assets/23341574/20107332/ff688a34-a58c-11e6-8b6a-d03cc37f8125.png)
![image](https://cloud.githubusercontent.com/assets/23341574/20107351/1a756324-a58d-11e6-9bef-104a77b1140b.png)

**Comment by webdigi** [comment]
If you click on to https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/exec can you see that the permissions are allowed? Use the account that you are using.

**Comment by WorkerBee099** [comment]
Here are my permissions.  Do I need to change one of them to fix this?

![image](https://cloud.githubusercontent.com/assets/23341574/20107723/651c25d8-a58e-11e6-923c-2eb57cf2111e.png)

**Comment by webdigi** [comment]
Thats weird. Can you please uninstall and install it again https://github.com/webdigi/GmailScheduler

**Comment by WorkerBee099** [comment]
Will do.  I'll test again later today.

**Comment by webdigi** [comment]
Please reopen if required.
