### ISSUE TITLE
Using 'send as' for an alternate 'from' reverts to gmail.com

### ISSUE THREAD

**Issue by carlsonb213** [webdigi/GmailScheduler#35]
I've added an @hotmail.com account to my @gmail.com account.  I create a message using 'from' my @hotmail.com account.  It remains correct in the draft message and the queued message.  But, when GmailScheduler sends it, it sends it from the @gmail.com account instead.

Maybe this is a feature request, but it would be nice if the 'from' was preserved.

If I get some time, I may take a look at fixing this for you, if there's not an API reason preventing it.

Great tool!!!  Thanks!

**Comment by webdigi** [comment]
thanks for posting. please submit a pull request and we can get it merged after testing.

**Comment by carlsonb213** [comment]
It looks like a minor change.  In Main.gs starting at line 79 the options are set.  
Adding 'from: message.getFrom(),' ought to do it.
Frankly, I haven't been doing AppScript for a while, but I'll give it a whirl.

**Comment by carlsonb213** [comment]
OK - I'm new to GitHub.  I created a 'fork', made the change that I had tested in my own copy of the project.  Then I created a pull request.  Hopefully, I did that right.

**Comment by webdigi** [comment]
@carlsonb213 - The commit is merged and initial tests ran as expected. Please check. 
Reopen ticket if the update does not work as expected.
