### ISSUE TITLE
Exact times don't match "x hours later"

### ISSUE THREAD

**Issue by dandv** [webdigi/GmailScheduler#37]
I'm trying to send an email at a precise time, say 8:30am. If it's 3:30am now and I enter "5 hours later", I get 8:30am. But if I enter "8:30am", I get some other time (right now, it's 16 hours off). I've set the timezone correctly (Pacific).

Screencast:
![exact times are four hours ahead](https://cloud.githubusercontent.com/assets/33569/23586907/60a31f4e-0154-11e7-8541-ede3311bb809.gif)

**Comment by dandv** [comment]
Or this:

![image](https://cloud.githubusercontent.com/assets/33569/23586913/a393d870-0154-11e7-87d9-802cce129fd1.png)

**Comment by webdigi** [comment]
Thanks for the gif.

To send an email at a precise time of say "8:30am" (including the same day) then you will have to set two labels. One label for "8:30am" and one label for "8:30am tomorrow". 

- If you are sending out the email at 3am then use the label "8:30 am" to send it out on the same day. 
- If you are sending out the email at 11am then use "8:30am tomorrow label".

I hope that makes sense. Please note that the issue you mentioned is only likely to be there in the front end while creating the labels. The backend label processing uses the timezone to send out the email correctly. 

Please test and reopen if you still have a problem.
