### ISSUE TITLE
Wrong account accesses

### ISSUE THREAD

**Issue by dcroal** [webdigi/GmailScheduler#39]
I find GmailScheduler to extremely useful and configurable, it's is also much less intrusive and resource-intensive on my low powered Chromebook than alternative solutions. 

The one issue I have is when I access Settings. I have two accounts on my Chromebook and https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/exec always takes me to settings for my secondary Google account, not my primary one. The only workaround I know of is to remove the secondary account from my Chromebook, change my GmailScheduler settings and then add back my secondary account. Any suggestions for a better way?

Thanks,

**Comment by dcroal** [comment]
Of course opening in an Incognitio window works too, BTW.

**Comment by webdigi** [comment]
@dcroal - thanks for your positive comments.

Unfortunately, this is a limitation with Google passing the account and there is nothing we can do about it.

**Comment by dcroal** [comment]
Thank you for the confirmation. I'll continue using Incognito to make changes.
