### ISSUE TITLE
Question about Privacy

### ISSUE THREAD

**Issue by tuur29** [webdigi/GmailScheduler#40]
Your readme mentions: 
> All your emails are private, unlike third party subscription programs that need access to your entire Gmail account with read and write access.

But I have to give the following permissions to the app:
- Read, send, delete, and manage your email
- Manage your calendars
- View and manage data associated with the application
- Allow this application to run when you are not present

That doesn't seem very private, especially since I can't audit the code on the google scripts platform. So I have to trust that the code on github is the same as on the google scripts platform.
Is there an easy way to upload a copy of the code to google scripts with my account?

**Comment by webdigi** [comment]
yes. the full code is available on this project and you can run it by yourself. see instructions in the github code on this project.
