### ISSUE TITLE
Authorization is required to perform that action.	288

### ISSUE THREAD

**Issue by Kevs88** [webdigi/GmailScheduler#43]
I am getting a huge code having this error and it is not letting me get the information from a form where I am using it. Anyone has an idea of what might be causing it?

**Comment by webdigi** [comment]
Did you click on this link and approve permissions? https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/exec

**Comment by tuur29** [comment]
Not the same person, but I get the same 3 emails (one for each trigger) each night with those "Authorization is required to perform that action" errors.

However I did approve the permissions and GmailScheduler shows up in my Google Settings

![image](https://user-images.githubusercontent.com/2472626/32945487-e699159a-cb93-11e7-845f-6bf4b9ba208f.png)

**Comment by webdigi** [comment]
Please try above link and remove permissions and add permissions again. Make sure you are using the same account.

**Comment by tuur29** [comment]
That didn't work, I'm still getting the same errors. I'm going back to using my own fork and let you know if that still works.

**Comment by tuur29** [comment]
Small update: I was able to fix my own fork by enabling the Gmail, Apps Script Execution and Calendar API in my Google Cloud Console for the project.

**Comment by webdigi** [comment]
Thanks for letting us know.
