### ISSUE TITLE
Could you explain the permissions?

### ISSUE THREAD

**Issue by cukabeka** [webdigi/GmailScheduler#44]
When approving a script to manage my inbox, I would love to know what the security implications are. Is there any chance some external server gets access to my account? Could you maybe elaborate on the readme?
However, I looked for a script like this for ages. Thanks for putting it up here!

**Comment by webdigi** [comment]
There are two ways to run this. 
Option 1) Simplest: Follow instructions here to send email https://github.com/webdigi/GmailScheduler 
The server is run on Google app script itself.

Option 2) Advanced: You have to go to https://www.google.com/script/start/ and then create all the files as required and manually run it. This means only the script in your account has access to your emails.
