### ISSUE TITLE
Permissions have changed?

### ISSUE THREAD

**Issue by partway** [webdigi/GmailScheduler#45]
I was excited by this because of the stated privacy concerns but it DOES in fact ask for permission to view, compose, send and delete email (see attached). Can anyone comment on this? 
![image](https://user-images.githubusercontent.com/40761531/42160899-e33412ca-7dc6-11e8-95d4-62d50d93f523.png)

**Comment by webdigi** [comment]
You can run this script under your own account. That way the permissions are only within your own script running on your google account.
