### ISSUE TITLE
Use the upcoming time

### ISSUE THREAD

**Issue by thapar** [webdigi/GmailScheduler#7]
Firstly, thank you for this wonderful extension. People like you make this world a better place!

I would like to create a label that is just 9am. This way, whether I'm writing the email at 1am (on the same day) or 4pm (the day before), it will always send at the next possible 9am. Currently, if the time is 4pm, and I try to create a label simply called "9am" it says the date has already passed. I'd like to make the logic a bit "smarter" by having it know to use the very next "9am".

Thanks again!

**Comment by webdigi** [comment]
Thanks for your suggestion & positive feedback.

Yes, this is an issue if the time is already passed. If the current time is 10am and you create a label to send email out at 11AM then it will accept that. One solution might be to tell the user the date is in the past but still allow creation. We will have a look at this in a future release.
