### ISSUE TITLE
Getting to GmailScheduler Settings

### ISSUE THREAD

**Issue by thapar** [webdigi/GmailScheduler#8]
Besides the email that was sent containing a link to get to my settings, how can I navigate to my settings without having that direct link? For example, if I was to delete that email by mistake, now how would I get to GmailScheduler's Settings page?

Thanks!

**Comment by roshanabraham** [comment]
You can always visit the gmail scheduler settings page with this link https://script.google.com/macros/s/AKfycbw6hnnKGeG6xUsbRE9c3WSvJibTbaW88DP9f83e8lFnc1v1kL0/exec
